### ISSUE TITLE
Can not get size image on android 10

### ISSUE THREAD

**Issue by thuynt99** [eXist-FraGGer/react-native-image-size#11]
- I get error when select image from SD card
- Error: unknown protocol: content
    at Object.promiseMethodWrapper [as getSize] (NativeModules.js:103)
    at _callee$ (index.js:48)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:145
    at tryCallOne (core.js:37)
    at core.js:123

**Comment by thanhluantl2304** [comment]
I got the answer. Replace these lines (in RNImageSizeModule.java )
` URL url = new URL(uri);
                Bitmap bitmap = BitmapFactory.decodeStream((InputStream) url.getContent()); `
with ` InputStream input = this.reactContext.getContentResolver().openInputStream(Uri.parse(uri));
                Bitmap bitmap = BitmapFactory.decodeStream((InputStream) input); `
Hope this help and i hope @eXist-FraGGer will update this next version

**Comment by eXist-FraGGer** [comment]
Hello guys, thank you and sorry for that huge delay.

@thanhluantl2304 @thuynt99 Unfortunately I am not able to test this, so please help me to test this version:
https://github.com/eXist-FraGGer/react-native-image-size/releases/tag/v.1.1.4

If it works fine - I will update the final release.

Thank you one more time!

**Comment by thanhluantl2304** [comment]
> Hello guys, thank you and sorry for that huge delay.
> 
> @thanhluantl2304 @thuynt99 Unfortunately I am not able to test this, so please help me to test this version: https://github.com/eXist-FraGGer/react-native-image-size/releases/tag/v.1.1.4
> 
> If it works fine - I will update the final release.
> 
> Thank you one more time!

<img width="1007" alt="Screen Shot 2022-01-12 at 15 07 25" src="https://user-images.githubusercontent.com/37209046/149088252-47474902-38b6-48b5-b5da-4cd14787c99e.png">
These are full changes, please re-check your commit please!

**Comment by Iman19845** [comment]
Hey @eXist-FraGGer,

Waiting for the release. Can I know the date of the release

**Comment by toluooshy** [comment]
If you are using expo I had a similar issue, then I made RNImageSize.android.js have the same exact code as RNImageSize.ios.js, and things started working!
