### ISSUE TITLE
Could not find com.android.tools.build:gradle:2.3.3.

### ISSUE THREAD

**Issue by cancit** [eXist-FraGGer/react-native-image-size#25]
It seems like `com.android.tools.build:gradle:2.3.3` package is deleted in maven repositories, both urls are returning 404
```
A problem occurred configuring project ':react-native-image-size'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':react-native-image-size:classpath'.
      > Could not find com.android.tools.build:gradle:2.3.3.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
          - https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
        Required by:
            project :react-native-image-size
```
https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom

**Comment by piotr-ponikowski-source** [comment]
I was about to ask the same question

**Comment by cancit** [comment]
Expensify team fixed this issue in their fork by downgrading gradle version to 2.3.0 https://github.com/Expensify/react-native-image-size/pull/5

**Comment by rsurgiewicz** [comment]
Same here, waiting for the fix

**Comment by skizzo** [comment]
Fixed this by changing the file `node_modules/react-native-image-size/android/`**`build.gradle`**:

❌ Old: `classpath 'com.android.tools.build:gradle:2.3.3'`
✅ New: **`classpath 'com.android.tools.build:gradle:2.3.0'`**

Afterwards, running `npx patch-package react-native-image-size` makes this change persistent across npm installs.
