### ISSUE TITLE
Android release bug fails

### ISSUE THREAD

**Issue by mralj** [eXist-FraGGer/react-native-image-size#4]
Hi!

Firstly thank you for creating this project, we have been using it while in development for our new app and it works 👍 

But, today when I tried to build signed apk, I couldn't due to problem with this plugin (I have double checked this, by removing plugin).

Here is command that I have run:  `./gradlew assembleRelease`
And here is error I got:

```
11:58:16.064 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:58:16.064 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:58:16.064 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:58:16.064 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':react-native-image-size:verifyReleaseResources'.
11:58:16.064 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed 
```

Please note that this is NOT happening running:
1. `react-native run-android`
2. `react-native run-android --variant="release"`

Both on device and emulator

**Comment by eXist-FraGGer** [comment]
Hello @mralj.
Thanks for your issue.
I have commented on your PR, let's fix it.
